# Generated by Django 4.2 on 2023-06-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todo'},
        ),
    ]
